---
apiVersion: v1
kind: Pod
metadata:
  name: curler
  namespace: airflow
spec:
  restartPolicy: Never
  containers:
  - name: base
    image: jacobnosal/alpine-curl-jq
    command: ["sleep"]
    env:
    - name: SOME_VARIABLE
      value: THE_VALUE
    args:
      - "30"
  - name: data-sidecar
    image: jacobnosal/alpine-curl-jq
    command: ["curl"]
    args:
      - "https://api2.binance.com/api/v3/ticker/24hr"

        
